image:
# - Visual Studio 2015
- Visual Studio 2017

build:
  parallel: true

platform:
  - x64

environment:
  CONDA_DIR: C:\Miniconda36-x64

init:
  - set PATH=%CONDA_DIR%;%CONDA_DIR%\Scripts;%CONDA_DIR%\Library\bin;%PATH%

build_script:
  - ci/appveyor/install.bat

test_script:
  - ci/appveyor/test.bat
