cc_test(
    name = "example-reverse-conditional",
    srcs = ["example-reverse-conditional.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)

cc_test(
    name = "example-reverse-gradient-derivatives-using-eigen",
    srcs = ["example-reverse-gradient-derivatives-using-eigen.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)

cc_test(
    name = "example-reverse-hessian-derivatives-using-eigen",
    srcs = ["example-reverse-hessian-derivatives-using-eigen.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)

cc_test(
    name = "example-reverse-higher-order-derivatives-multi-variable-function",
    srcs = ["example-reverse-higher-order-derivatives-multi-variable-function.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)

cc_test(
    name = "example-reverse-higher-order-derivatives-single-variable-function",
    srcs = ["example-reverse-higher-order-derivatives-single-variable-function.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)

cc_test(
    name = "example-reverse-multi-variable-function-with-parameters",
    srcs = ["example-reverse-multi-variable-function-with-parameters.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)

cc_test(
    name = "example-reverse-multi-variable-function",
    srcs = ["example-reverse-multi-variable-function.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)

cc_test(
    name = "example-reverse-single-variable-function",
    srcs = ["example-reverse-single-variable-function.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)