cc_test(
    name = "example-forward-single-variable-function",
    srcs=["example-forward-single-variable-function.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)

cc_test(
    name = "example-forward-single-variable-function-custom-scalar",
    srcs = ["example-forward-single-variable-function-custom-scalar.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)

cc_test(
    name = "example-forward-multi-variable-function",
    srcs=["example-forward-multi-variable-function.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)

cc_test(
    name = "example-forward-multi-variable-function-with-parameters",
    srcs = ["example-forward-multi-variable-function-with-parameters.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)

cc_test(
    name = "example-forward-jacobian-derivatives-using-eigen",
    srcs = ["example-forward-jacobian-derivatives-using-eigen.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)

cc_test(
    name = "example-forward-jacobian-derivatives-using-eigen-with-scalar",
    srcs = ["example-forward-jacobian-derivatives-using-eigen-with-scalar.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)

cc_test(
    name = "example-forward-jacobian-derivatives-using-eigen-with-parameters",
    srcs = ["example-forward-jacobian-derivatives-using-eigen-with-parameters.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)

cc_test(
    name = "example-forward-higher-order-derivatives",
    srcs = ["example-forward-higher-order-derivatives.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)

cc_test(
    name = "example-forward-hessian-derivatives-using-eigen",
    srcs = ["example-forward-hessian-derivatives-using-eigen.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)

cc_test(
    name = "example-forward-hessian-derivatives-using-eigen-with-scalar",
    srcs = ["example-forward-hessian-derivatives-using-eigen-with-scalar.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)

cc_test(
    name = "example-forward-hessian-derivatives-using-eigen-with-parameters",
    srcs = ["example-forward-hessian-derivatives-using-eigen-with-parameters.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)

cc_test(
    name = "example-forward-gradient-derivatives-using-eigen",
    srcs = ["example-forward-gradient-derivatives-using-eigen.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)

cc_test(
    name = "example-forward-gradient-derivatives-using-eigen-with-scalar",
    srcs = ["example-forward-gradient-derivatives-using-eigen-with-scalar.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)

cc_test(
    name = "example-forward-gradient-derivatives-using-eigen-with-parameters",
    srcs = ["example-forward-gradient-derivatives-using-eigen-with-parameters.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)



