cc_test(
    name = "example-forward-directional-taylor-series-using-eigen",
    srcs = ["example-forward-directional-taylor-series-using-eigen.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)

cc_test(
    name = "example-forward-directional-taylor-series",
    srcs = ["example-forward-directional-taylor-series.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)

cc_test(
    name = "example-forward-gradient-derivatives-using-eigen-with-parameters",
    srcs = ["example-forward-gradient-derivatives-using-eigen-with-parameters.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)

cc_test(
    name = "example-forward-gradient-derivatives-using-eigen",
    srcs = ["example-forward-gradient-derivatives-using-eigen.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)

cc_test(
    name = "example-forward-gradient-derivatives",
    srcs = ["example-forward-gradient-derivatives.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)

cc_test(
    name = "example-forward-hessian-derivatives-using-eigen-with-parameters",
    srcs = ["example-forward-hessian-derivatives-using-eigen-with-parameters.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)

cc_test(
    name = "example-forward-hessian-derivatives-using-eigen",
    srcs = ["example-forward-hessian-derivatives-using-eigen.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)

cc_test(
    name = "example-forward-higher-order-cross-derivatives",
    srcs = ["example-forward-higher-order-cross-derivatives.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)

cc_test(
    name = "example-forward-higher-order-directional-derivatives-using-eigen",
    srcs = ["example-forward-higher-order-directional-derivatives-using-eigen.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)

cc_test(
    name = "example-forward-higher-order-directional-derivatives",
    srcs = ["example-forward-higher-order-directional-derivatives.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)

cc_test(
    name = "example-forward-jacobian-derivatives-using-eigen",
    srcs = ["example-forward-jacobian-derivatives-using-eigen.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)

cc_test(
    name = "example-forward-jacobian-derivatives-using-eigen-with-parameters",
    srcs = ["example-forward-jacobian-derivatives-using-eigen-with-parameters.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)

cc_test(
    name = "example-forward-jacobian-derivatives-using-eigen-map",
    srcs = ["example-forward-jacobian-derivatives-using-eigen-map.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)

cc_test(
    name = "example-forward-multi-variable-function-with-parameters",
    srcs = ["example-forward-multi-variable-function-with-parameters.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)

cc_test(
    name = "example-forward-multi-variable-function",
    srcs = ["example-forward-multi-variable-function.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)

cc_test(
    name = "example-forward-single-variable-function-custom-scalar",
    srcs = ["example-forward-single-variable-function-custom-scalar.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)

cc_test(
    name = "example-forward-single-variable-function",
    srcs = ["example-forward-single-variable-function.cpp"],
    deps = ["//:autodiff"],
    copts = ["-I./"]
)
