name: windows

on:
  push:
    branches:
      - master

  pull_request:

  schedule:
    - cron: "0 5 * * 1"  # runs at 05:00 UTC on Mondays

jobs:
  build:

    runs-on: windows-latest
    env:
      configuration: Release
    strategy:
      fail-fast: true
      max-parallel: 4

    steps:
    - uses: actions/checkout@v1
    - uses: goanpeca/setup-miniconda@v1.0.2
      with:
        auto-update-conda: true
    - name: Install
      shell: cmd /C CALL {0}
      run: |
        conda config --add channels conda-forge
        conda install conda-devenv
        conda info -a
        conda devenv
    - name: Build
      shell: cmd /C CALL {0}
      run: |
        call activate autodiff
        cmake -S . -B build
        cmake --build build --config ${{ env.configuration }} --target install
    - name: Tests
      shell: cmd /C CALL {0}
      run: call build\test\${{ env.configuration }}\tests.exe
