name: windows

# on:
#   push:
#     branches:
#       - master

#   pull_request:
#     branches:
#       - master

on: push

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      max-parallel: 4
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest
            configuration: Release

    steps:
    - uses: actions/checkout@v1
    - name: Setup environment variables
      run: |
        set CONDA_DIR: "C:\Miniconda36-x64"
        echo ${env:CONDA}
        echo ${env:PATH}
    - name: Setup conda and install
      run: |
        ${env:CONDA}\Scripts\conda.exe config --set always_yes yes --set changeps1 no
        ${env:CONDA}\Scripts\conda.exe config --add channels conda-forge
        ${env:CONDA}\Scripts\conda.exe install conda-devenv
        ${env:CONDA}\Scripts\conda.exe update -q conda
        ${env:CONDA}\Scripts\conda.exe info -a
        ${env:CONDA}\Scripts\conda.exe devenv
        call activate autodiff
    - name: Build
      run: | 
        cmake -S . -B build
        cmake --build build --config ${{ matrix.configuration }} --target install
    - name: Tests
      run: call build\test\${{ matrix.configuration }}\tests.exe
